### ISSUE TITLE
firefox-pipewire hash mismatch

### ISSUE THREAD

**Issue by efouladi** [calbrecht/nixpkgs-overlays#1]
Hey, 
I'm getting a hash mismatch when trying to use your overlay

`hash mismatch in fixed-output derivation '/nix/store/xfjbymngjakrlharv4b0lb0x3d2rfpf4-firefox-pipewire-0-3.patch':
  wanted: sha256:0h02365ybwfkrs55b1a701mf2qb617zkc9lmbid6w2f6w996rfz3
  got:    sha256:1ijgkg55dc9c9mwx376vgkbc6r9hzxvrg1n4li4m3hna94b8cmp3`

**Comment by calbrecht** [comment]
Yes, me too. And also if i put in the hash that is given on the cli, it fails to apply. Weird, i had this once already that it seemed like the fedora patch has changed despite me not changing the url.

I will try to find out what is happening.

**Comment by efouladi** [comment]
I think the problem is that you're using the blob url which doesn't give the correct patch. I think If you just use the raw instead it would work

**Comment by calbrecht** [comment]
Ok, i will see. In the meantime i will find the correct patch in my nix-store and put it in the repo.

**Comment by efouladi** [comment]
Thanks. BTW if you use nix-prefetch-url repeatedly with the same (blob) url you'll see that it gives you a different hash every time

**Comment by calbrecht** [comment]
oh noes, i did not notice that. Thank you :)

**Comment by calbrecht** [comment]
I changed the url to the raw patch. And updated the hash. Probably i had downloaded it and wanted to put it in the repo but decided otherwise after it was build successfully.

@efouladi :+1:  Thanks for trying it out and notifying me.

**Comment by calbrecht** [comment]
I found it in the closure of my currently running firefox. It is the same as the one that is referenced now in the overlay. Thanks again.

**Comment by efouladi** [comment]
No worries. Keep up the good work :)
